import assert from "node:assert/strict"; import test from "node:test"; import { findExactStakeholderMatch, parseStakeholderSimilarityResponse, parseStakeholderSimilarityResponseWithIssue, stakeholderSimilarityDiagnosticCategory, summarizeStakeholderSimilarityResponse } from "../lib/stakeholder-similarity.ts";
const base = { assessmentSubject: "Vendor service", identifiedConcern: "Recovery controls are unclear", possibleOutcome: "Customer notices delayed" };
test("matches identical stakeholder submissions", () => assert.equal(findExactStakeholderMatch(base, [{ id: "one", source: base }])?.id, "one"));
test("normalizes capitalization and whitespace", () => assert.equal(findExactStakeholderMatch({ assessmentSubject: " VENDOR   SERVICE ", identifiedConcern: "recovery controls are unclear", possibleOutcome: "customer notices delayed" }, [{ id: "one", source: base }])?.id, "one"));
test("does not exact-match different risk content", () => assert.equal(findExactStakeholderMatch({ ...base, identifiedConcern: "Customer data disclosure" }, [{ id: "one", source: base }]), undefined));

const nonMatch = { potentiallySimilar: false, matchingSubmissionId: null, rationale: "The underlying risk scenario differs." };
const match = { potentiallySimilar: true, matchingSubmissionId: "submission-1", rationale: "The same vendor recovery concern is described." };
test("parses top-level stakeholder similarity output", () => assert.deepEqual(parseStakeholderSimilarityResponse({ output_text: JSON.stringify(nonMatch) }), nonMatch));
test("parses raw Responses API stakeholder similarity output", () => assert.deepEqual(parseStakeholderSimilarityResponse({ output: [{ content: [{ type: "output_text", text: JSON.stringify(match) }] }] }), match));
test("rejects malformed and missing stakeholder similarity output", () => { assert.equal(parseStakeholderSimilarityResponse({ output_text: "{" }), undefined); assert.equal(parseStakeholderSimilarityResponse({}), undefined); });
test("rejects structurally invalid stakeholder similarity output", () => { assert.equal(parseStakeholderSimilarityResponse({ output_text: JSON.stringify({ potentiallySimilar: true, rationale: "Missing ID" }) }), undefined); assert.equal(parseStakeholderSimilarityResponse({ output_text: JSON.stringify({ potentiallySimilar: "true", matchingSubmissionId: "submission-1", rationale: "Wrong type" }) }), undefined); });
test("categorizes missing and invalid structured similarity output without source data", () => { assert.deepEqual(parseStakeholderSimilarityResponseWithIssue({ output: [] }), { result: undefined, issue: "NO_USABLE_OUTPUT" }); assert.deepEqual(parseStakeholderSimilarityResponseWithIssue({ output_text: "{" }), { result: undefined, issue: "STRUCTURED_OUTPUT_PARSE_ERROR" }); const diagnostics = summarizeStakeholderSimilarityResponse({ status: "incomplete", incomplete_details: { reason: "max_output_tokens" }, output: [{ type: "message", content: [{ type: "refusal" }] }] }); assert.deepEqual(diagnostics, { hasTopLevelOutputText: false, hasNestedOutputText: false, outputTypes: ["message"], contentTypes: ["refusal"], responseStatus: "incomplete", incompleteReason: "max_output_tokens", hasRefusal: true }); assert.equal(JSON.stringify(diagnostics).includes("Vendor service"), false); });
test("categorizes OpenAI transport and response failures safely", () => { assert.equal(stakeholderSimilarityDiagnosticCategory({ httpError: true }), "OPENAI_HTTP_ERROR"); assert.equal(stakeholderSimilarityDiagnosticCategory({ responseJsonError: true }), "OPENAI_RESPONSE_JSON_ERROR"); assert.equal(stakeholderSimilarityDiagnosticCategory({ parseIssue: "NO_USABLE_OUTPUT" }), "NO_USABLE_OUTPUT"); assert.equal(stakeholderSimilarityDiagnosticCategory({ parseIssue: "STRUCTURED_OUTPUT_PARSE_ERROR" }), "STRUCTURED_OUTPUT_PARSE_ERROR"); assert.equal(stakeholderSimilarityDiagnosticCategory({ diagnostics: { hasTopLevelOutputText: false, hasNestedOutputText: false, outputTypes: ["message"], contentTypes: ["refusal"], responseStatus: "completed", incompleteReason: undefined, hasRefusal: true } }), "OPENAI_REFUSAL"); assert.equal(stakeholderSimilarityDiagnosticCategory({ diagnostics: { hasTopLevelOutputText: false, hasNestedOutputText: false, outputTypes: [], contentTypes: [], responseStatus: "incomplete", incompleteReason: "max_output_tokens", hasRefusal: false } }), "OPENAI_INCOMPLETE_OUTPUT"); });
