export function normalizeStakeholderRisk(source: Record<string, string>) { return ["assessmentSubject", "businessPurpose", "businessOwner", "identifiedConcern", "possibleOutcome", "affectedAreas", "existingSafeguards", "additionalContext", "stakeholderFindings"].map((key) => (source[key] ?? "").toLowerCase().trim().replace(/\s+/g, " ").replace(/[^\w\s]/g, "")).join("|"); }
export function findExactStakeholderMatch(candidate: Record<string, string>, submissions: Array<{ id: string; source: Record<string, string> }>) { const normalized = normalizeStakeholderRisk(candidate); return submissions.find((submission) => normalizeStakeholderRisk(submission.source) === normalized); }

export type StakeholderSimilarity = { potentiallySimilar: boolean; matchingSubmissionId: string | null; rationale: string };
export function isStakeholderSimilarity(value: unknown): value is StakeholderSimilarity { if (!value || typeof value !== "object") return false; const result = value as Record<string, unknown>; return typeof result.potentiallySimilar === "boolean" && typeof result.rationale === "string" && (typeof result.matchingSubmissionId === "string" || result.matchingSubmissionId === null); }
type SimilarityResponse = { output_text?: unknown; status?: unknown; incomplete_details?: { reason?: unknown }; output?: Array<{ type?: unknown; content?: Array<{ type?: unknown; text?: unknown }> }> };
export type SimilarityResponseDiagnostics = { hasTopLevelOutputText: boolean; hasNestedOutputText: boolean; outputTypes: string[]; contentTypes: string[]; responseStatus: string | undefined; incompleteReason: string | undefined; hasRefusal: boolean };
export type SimilarityParseIssue = "NO_USABLE_OUTPUT" | "STRUCTURED_OUTPUT_PARSE_ERROR";
export type SimilarityDiagnosticCategory = "OPENAI_HTTP_ERROR" | "OPENAI_RESPONSE_JSON_ERROR" | "NO_USABLE_OUTPUT" | "STRUCTURED_OUTPUT_PARSE_ERROR" | "OPENAI_INCOMPLETE_OUTPUT" | "OPENAI_REFUSAL" | "UNEXPECTED_ROUTE_ERROR";

function responseText(response: SimilarityResponse) { return typeof response.output_text === "string" && response.output_text ? response.output_text : response.output?.flatMap((item) => item.content ?? []).filter((item) => item.type === "output_text").map((item) => typeof item.text === "string" ? item.text : "").join(""); }
export function summarizeStakeholderSimilarityResponse(payload: unknown): SimilarityResponseDiagnostics { const response = payload && typeof payload === "object" ? payload as SimilarityResponse : {}; const content = response.output?.flatMap((item) => item.content ?? []) ?? []; return { hasTopLevelOutputText: typeof response.output_text === "string" && Boolean(response.output_text.trim()), hasNestedOutputText: content.some((item) => item.type === "output_text" && typeof item.text === "string" && Boolean(item.text.trim())), outputTypes: [...new Set((response.output ?? []).map((item) => typeof item.type === "string" ? item.type : "unknown"))], contentTypes: [...new Set(content.map((item) => typeof item.type === "string" ? item.type : "unknown"))], responseStatus: typeof response.status === "string" ? response.status : undefined, incompleteReason: typeof response.incomplete_details?.reason === "string" ? response.incomplete_details.reason : undefined, hasRefusal: content.some((item) => item.type === "refusal") }; }
export function parseStakeholderSimilarityResponseWithIssue(payload: unknown): { result: StakeholderSimilarity | undefined; issue: SimilarityParseIssue | undefined } { if (!payload || typeof payload !== "object") return { result: undefined, issue: "NO_USABLE_OUTPUT" }; const text = responseText(payload as SimilarityResponse); if (!text?.trim()) return { result: undefined, issue: "NO_USABLE_OUTPUT" }; try { const result = JSON.parse(text); return isStakeholderSimilarity(result) ? { result, issue: undefined } : { result: undefined, issue: "STRUCTURED_OUTPUT_PARSE_ERROR" }; } catch { return { result: undefined, issue: "STRUCTURED_OUTPUT_PARSE_ERROR" }; } }
export function parseStakeholderSimilarityResponse(payload: unknown): StakeholderSimilarity | undefined { return parseStakeholderSimilarityResponseWithIssue(payload).result; }
export function stakeholderSimilarityDiagnosticCategory(options: { httpError?: boolean; responseJsonError?: boolean; diagnostics?: SimilarityResponseDiagnostics; parseIssue?: SimilarityParseIssue }): SimilarityDiagnosticCategory { if (options.httpError) return "OPENAI_HTTP_ERROR"; if (options.responseJsonError) return "OPENAI_RESPONSE_JSON_ERROR"; if (options.diagnostics?.responseStatus === "incomplete") return "OPENAI_INCOMPLETE_OUTPUT"; if (options.diagnostics?.hasRefusal) return "OPENAI_REFUSAL"; return options.parseIssue ?? "UNEXPECTED_ROUTE_ERROR"; }
