export function normalizeStakeholderRisk(source: Record<string, string>) { return ["assessmentSubject", "businessPurpose", "businessOwner", "identifiedConcern", "possibleOutcome", "affectedAreas", "existingSafeguards", "additionalContext", "stakeholderFindings"].map((key) => (source[key] ?? "").toLowerCase().trim().replace(/\s+/g, " ").replace(/[^\w\s]/g, "")).join("|"); }
export function findExactStakeholderMatch(candidate: Record<string, string>, submissions: Array<{ id: string; source: Record<string, string> }>) { const normalized = normalizeStakeholderRisk(candidate); return submissions.find((submission) => normalizeStakeholderRisk(submission.source) === normalized); }

export type StakeholderSimilarity = { potentiallySimilar: boolean; matchingSubmissionId: string | null; rationale: string };
export function isStakeholderSimilarity(value: unknown): value is StakeholderSimilarity { if (!value || typeof value !== "object") return false; const result = value as Record<string, unknown>; return typeof result.potentiallySimilar === "boolean" && typeof result.rationale === "string" && (typeof result.matchingSubmissionId === "string" || result.matchingSubmissionId === null); }
type SimilarityResponse = { output_text?: unknown; output?: Array<{ content?: Array<{ type?: unknown; text?: unknown }> }> };

function responseText(response: SimilarityResponse) { return typeof response.output_text === "string" && response.output_text ? response.output_text : response.output?.flatMap((item) => item.content ?? []).filter((item) => item.type === "output_text").map((item) => typeof item.text === "string" ? item.text : "").join(""); }
export function parseStakeholderSimilarityResponse(payload: unknown): StakeholderSimilarity | undefined { if (!payload || typeof payload !== "object") return undefined; const text = responseText(payload as SimilarityResponse); if (!text?.trim()) return undefined; try { const result = JSON.parse(text); return isStakeholderSimilarity(result) ? result : undefined; } catch { return undefined; } }
