import { executiveAnalysisSchema, parseExecutiveAnalysisResponse } from "@/lib/grc/executive-analysis";

const instructions = `You are preparing an AI-assisted executive risk analysis draft for senior management. Analyze the supplied human-approved Risk Register records as a portfolio. Your purpose is to surface supported cross-risk patterns, concentrations, common weaknesses, dependencies, compounding exposure, coordinated treatment opportunities, and assessment confidence that are not apparent from reading records one by one.

Use only the supplied approved records. Do not invent incidents, vendors, controls, control effectiveness, financial amounts, regulations, legal conclusions, compliance failures, residual risk, risk appetite, historical trends, or business consequences. Do not change or recalculate likelihood, impact, score, rating, treatment strategy, or analyst conclusions. If evidence is insufficient, state the specific uncertainty and affected Risk IDs rather than filling the gap. The draft is advisory and requires human review.

Write concise, specific executive prose. Synthesis is more important than length; do not narrate the register row by row, repeat the same fact across sections, or use counts and ratings as a substitute for analysis. Reference only supplied Risk IDs. Use empty arrays for decisions or escalations that the records do not genuinely support.

For a portfolio of roughly 2-5 risks, aim for approximately 500-800 words total when the evidence supports it. For 1-2 risks, write proportionately less without padding.

Required sections:
- overallRiskPosture: a substantive 100-150 word overview for a small portfolio. Explain severity and concentration, what is most significant, why it matters to management, and context affecting interpretation. Do not merely state a rating or count.
- keyRiskThemes: normally 2-4 themes when supported. Each title and analysis should explain the shared pattern, why related risks belong together, what the concentration means, and include relatedRiskIds. Do not create one theme per risk unless no supported cross-risk relationship exists.
- materialExposure: approximately 100-150 words for a small portfolio. Connect approved technical or operational conditions to only the documented collective business consequences.
- interdependencies: approximately 80-130 words when meaningful relationships exist. Explain shared vendors, technology, controls, processes, cumulative operational impact, or how one exposure could worsen another. If no meaningful relationship is established, say that explicitly.
- assessmentUncertainty: approximately 80-130 words when uncertainty exists. Identify the specific missing evidence, assumptions, unknown control capability, recovery visibility, or validation gap; name affected Risk IDs and explain why it matters.
- managementPriorities: normally 2-4 consolidated priorities. Each must explain the exposure addressed, why management attention is warranted, whether it helps multiple risks, and include relatedRiskIds. Do not simply restate one treatment action per risk or make treatment decisions.
- decisionsAndEscalations: include only genuine management decisions, escalations, evidence validation, assumption confirmation, ownership clarification, or control-capability confirmation supported by the records. This may be empty.
- nextSteps: normally 3-5 practical, consolidated actions drawn from approved treatment information, priorities, uncertainty, or validation needs. Include rationale and relatedRiskIds; do not introduce unrelated GRC work.`;

export async function POST(request: Request) { if (!process.env.OPENAI_API_KEY) return Response.json({ error: "AI executive analysis is not configured." }, { status: 503 }); try { const body = await request.json(); if (!Array.isArray(body?.risks) || !body.risks.length) return Response.json({ error: "Approved Risk Register records are required." }, { status: 400 }); const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4o-mini", store: false, max_output_tokens: 2400, instructions, input: JSON.stringify({ reportDate: body.reportDate, risks: body.risks }), text: { format: { type: "json_schema", name: "executive_risk_analysis", strict: true, schema: executiveAnalysisSchema } } }) }); if (!response.ok) return Response.json({ error: "The AI service could not prepare executive analysis." }, { status: 502 }); const payload = await response.json(); const analysis = parseExecutiveAnalysisResponse(payload); if (!analysis) return Response.json({ error: "The AI service returned incomplete executive analysis." }, { status: 502 }); return Response.json({ analysis }); } catch { return Response.json({ error: "Unable to prepare executive analysis right now." }, { status: 500 }); } }
