import { heatMapExportModel, portfolioSummary } from "./heat-map.ts";
import type { RiskRegisterRecord } from "./risk-register.ts";

const severity = { Critical: 4, High: 3, Medium: 2, Low: 1 } as const;

export function reportDate(date = new Date()) { return date.toISOString().slice(0, 10); }
export function orderForManagementAttention(records: RiskRegisterRecord[]) { return [...records].sort((a, b) => severity[b.riskRating] - severity[a.riskRating] || b.riskScore - a.riskScore || a.id.localeCompare(b.id)); }
export function executiveReportModel(records: RiskRegisterRecord[], date = new Date()) { return { reportDate: reportDate(date), summary: portfolioSummary(records), heatMap: heatMapExportModel(records), attention: orderForManagementAttention(records), transparency: assessmentTransparency(records), narrativeRisks: records.map(({ id, asset, riskRating, riskScore, riskStatement, businessImpact, riskOwner, treatmentStrategy, status, targetDate }) => ({ id, asset, riskRating, riskScore, riskStatement, businessImpact, riskOwner, treatmentStrategy, status, targetDate })) }; }
export function assessmentTransparency(records: RiskRegisterRecord[]) { const collect = (key: "assumptions" | "uncertainties" | "missingInformation") => Object.entries(records.reduce<Record<string, string[]>>((result, record) => { for (const item of record[key] ?? []) { const normalized = item.toLowerCase().trim(); if (normalized) result[normalized] = [...(result[normalized] ?? []), record.id]; } return result; }, {})).map(([item, ids]) => ({ item, ids })); return { assumptions: collect("assumptions"), uncertainties: collect("uncertainties"), informationGaps: collect("missingInformation") }; }
export function portfolioThemes(records: RiskRegisterRecord[]) { const themes: string[] = []; const owners = records.reduce<Record<string, number>>((all, risk) => ({ ...all, [risk.riskOwner]: (all[risk.riskOwner] ?? 0) + 1 }), {}); for (const [owner, count] of Object.entries(owners)) if (owner && count > 1) themes.push(`${count} registered risks are concentrated with ${owner}.`); const strategies = records.reduce<Record<string, number>>((all, risk) => ({ ...all, [risk.treatmentStrategy]: (all[risk.treatmentStrategy] ?? 0) + 1 }), {}); for (const [strategy, count] of Object.entries(strategies)) if (count > 1) themes.push(`${count} risks share a ${strategy.toLowerCase()} treatment direction.`); return themes.slice(0, 4); }
export function managementConsiderations(records: RiskRegisterRecord[]) { const actions: string[] = []; const attention = orderForManagementAttention(records); if (attention.some((risk) => risk.riskRating === "Critical" || risk.riskRating === "High")) actions.push("Prioritize treatment progress for Critical and High risks."); if (attention.some((risk) => risk.status === "Open" || risk.status === "Treatment Planned")) actions.push("Monitor open and planned treatment activity against approved target dates."); if (attention.some((risk) => risk.treatmentStrategy === "Accept")) actions.push("Maintain scheduled oversight of accepted risks under established review practices."); return actions.slice(0, 5); }
export function nextSteps(records: RiskRegisterRecord[]) { return orderForManagementAttention(records).filter((risk) => risk.status !== "Closed").slice(0, 4).map((risk) => `${risk.id}: ${risk.treatmentPlan || `Monitor ${risk.treatmentStrategy.toLowerCase()} activity`} by ${risk.riskOwner || "the assigned risk owner"} for ${risk.targetDate || "the approved target date"}.`); }
export function cleanExecutiveNarrative(value: string) { return value.replace(/#{1,6}/g, "").replace(/\*\*/g, "").replace(/---+/g, "").replace(/\n{3,}/g, "\n\n").trim(); }
