export type ExecutiveAnalysis = { overallRiskPosture: string; keyRiskThemes: Array<{ title: string; analysis: string; relatedRiskIds: string[] }>; materialExposure: string; interdependencies: string; assessmentUncertainty: string; managementPriorities: Array<{ title: string; rationale: string; relatedRiskIds: string[] }>; decisionsAndEscalations: Array<{ title: string; rationale: string; relatedRiskIds: string[] }>; nextSteps: Array<{ action: string; rationale: string; relatedRiskIds: string[] }> };
export const executiveAnalysisInstructions = `You are preparing an AI-assisted executive risk analysis draft for senior management. Analyze the supplied human-approved Risk Register records as a portfolio. Your purpose is to surface supported cross-risk patterns, concentrations, common weaknesses, dependencies, compounding exposure, coordination among approved treatment actions, and assessment confidence that are not apparent from reading records one by one.

Use only the supplied approved records. Ground every statement, priority, action, and implication in the supplied risk/source information, approved treatment strategy, approved treatment action/plan, documented control gap, documented uncertainty, documented business impact, or documented validation/escalation need. Do not invent incidents, vendors, controls, control effectiveness, financial amounts, regulations, legal conclusions, compliance failures, residual risk, risk appetite, historical trends, or business consequences. Do not introduce a new substantive management action, including training, automation, monitoring, technologies, tooling, teams, staffing, policies, programs, assessments, vendor-management processes, identity upgrades, communication programs, or incident-response capabilities, unless it is supported by the supplied records. Do not change or recalculate likelihood, impact, score, rating, treatment strategy, or analyst conclusions. If evidence is insufficient, state the specific uncertainty and affected Risk IDs rather than filling the gap with a recommendation. The draft is advisory and requires human review.

Write concise, specific executive prose. Synthesis is more important than length; do not narrate the register row by row, repeat the same fact across sections, or use counts and ratings as a substitute for analysis. Reference only supplied Risk IDs. Use empty arrays for decisions or escalations that the records do not genuinely support.

For a portfolio of roughly 2-5 risks, aim for approximately 500-800 words total when the evidence supports it. For 1-2 risks, write proportionately less without padding.

Required sections:
- overallRiskPosture: a substantive 100-150 word overview for a small portfolio. Explain severity and concentration, what is most significant, why it matters to management, and context affecting interpretation. Do not merely state a rating or count.
- keyRiskThemes: normally 2-4 themes when supported. Each title and analysis should explain the shared pattern, why related risks belong together, what the concentration means, and include relatedRiskIds. Do not create one theme per risk unless no supported cross-risk relationship exists.
- materialExposure: approximately 100-150 words for a small portfolio. Connect approved technical or operational conditions to only the documented collective business consequences.
- interdependencies: approximately 80-130 words when meaningful relationships exist. Explain shared vendors, technology, controls, processes, cumulative operational impact, or how one exposure could worsen another, only when supported by the records. If no meaningful relationship is established, say that explicitly.
- assessmentUncertainty: approximately 80-130 words when uncertainty exists. Identify the specific missing evidence, assumptions, unknown control capability, recovery visibility, or validation gap; name affected Risk IDs and explain why it matters.
- managementPriorities: normally 2-4 consolidated priorities. Each must be traceable to one or more approved treatment strategies/actions, documented control gaps, documented assessment uncertainties, documented business impacts, or documented validation/escalation needs. Explain the exposure addressed, why management attention is warranted, whether it helps multiple risks, and include relatedRiskIds. Do not make new treatment decisions or introduce unsupported actions. It is acceptable to provide fewer priorities.
- decisionsAndEscalations: include only genuine management decisions, escalations, evidence validation, assumption confirmation, ownership clarification, or control-capability confirmation supported by the records. This may be empty.
- nextSteps: normally 3-5 practical, consolidated actions that are traceable to approved treatment actions, documented priorities, uncertainty, or validation needs. Include rationale and relatedRiskIds. Do not introduce a new substantive action or unrelated GRC work. It is acceptable to provide fewer next steps.`;
export const executiveAnalysisSchema = { type: "object", additionalProperties: false, properties: { overallRiskPosture: { type: "string" }, keyRiskThemes: { type: "array", items: { type: "object", additionalProperties: false, properties: { title: { type: "string" }, analysis: { type: "string" }, relatedRiskIds: { type: "array", items: { type: "string" } } }, required: ["title", "analysis", "relatedRiskIds"] } }, materialExposure: { type: "string" }, interdependencies: { type: "string" }, assessmentUncertainty: { type: "string" }, managementPriorities: { type: "array", items: { type: "object", additionalProperties: false, properties: { title: { type: "string" }, rationale: { type: "string" }, relatedRiskIds: { type: "array", items: { type: "string" } } }, required: ["title", "rationale", "relatedRiskIds"] } }, decisionsAndEscalations: { type: "array", items: { type: "object", additionalProperties: false, properties: { title: { type: "string" }, rationale: { type: "string" }, relatedRiskIds: { type: "array", items: { type: "string" } } }, required: ["title", "rationale", "relatedRiskIds"] } }, nextSteps: { type: "array", items: { type: "object", additionalProperties: false, properties: { action: { type: "string" }, rationale: { type: "string" }, relatedRiskIds: { type: "array", items: { type: "string" } } }, required: ["action", "rationale", "relatedRiskIds"] } } }, required: ["overallRiskPosture", "keyRiskThemes", "materialExposure", "interdependencies", "assessmentUncertainty", "managementPriorities", "decisionsAndEscalations", "nextSteps"] } as const;
const strings = (value: unknown) => Array.isArray(value) && value.every((item) => typeof item === "string");
const items = (value: unknown, label: "title" | "action", body: "analysis" | "rationale") => Array.isArray(value) && value.every((item) => !!item && typeof item === "object" && typeof (item as Record<string, unknown>)[label] === "string" && typeof (item as Record<string, unknown>)[body] === "string" && strings((item as Record<string, unknown>).relatedRiskIds));
export function isExecutiveAnalysis(value: unknown): value is ExecutiveAnalysis { if (!value || typeof value !== "object") return false; const item = value as Record<string, unknown>; return ["overallRiskPosture", "materialExposure", "interdependencies", "assessmentUncertainty"].every((key) => typeof item[key] === "string") && items(item.keyRiskThemes, "title", "analysis") && items(item.managementPriorities, "title", "rationale") && items(item.decisionsAndEscalations, "title", "rationale") && items(item.nextSteps, "action", "rationale"); }
export function parseExecutiveAnalysisResponse(payload: unknown): ExecutiveAnalysis | undefined { if (!payload || typeof payload !== "object") return undefined; const response = payload as { output_text?: unknown; output?: Array<{ content?: Array<{ type?: string; text?: string }> }> }; const text = typeof response.output_text === "string" && response.output_text ? response.output_text : response.output?.flatMap((item) => item.content ?? []).filter((item) => item.type === "output_text").map((item) => item.text ?? "").join(""); try { const analysis = JSON.parse(text || "{}"); return isExecutiveAnalysis(analysis) ? analysis : undefined; } catch { return undefined; } }
